apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-postgres
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 50001  # Porta que será exposta no nó
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: django-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
